nota1= float(input("digite a nota"))
nota2= float(input("digite a nota"))
nota3= float(input("digite a nota"))
nota4= float(input("digite a nota"))
media= (nota1+nota2+nota3+nota4)/4
print("Primeira nota: %.1f"% (nota1))
print("Segunda nota: %.1f"% (nota2))
print("Terceira nota: %.1f"% (nota3))
print("Quarta nota: %.1f"% (nota4))
print("Média:%.1f"%(media))
